### ISSUE TITLE
表示感谢！另外那个代码片段的高亮增加下？

### ISSUE THREAD

**Issue by HogwartsRico** [phoenixlzx/MinoriWiki#1]
已经在公司内网上搭了个Wiki，很方便。  
就是代码高亮没有，不知能否增加下CSS代码高亮渲染？  
![img](http://ww3.sinaimg.cn/large/6ff04438gw1ercyhxw0d6j20o40gmabq.jpg)  
另外，再次表示感谢!

**Comment by phoenixlzx** [comment]
已经更新。 `npm install minori` 来安装下新版本，之前的目录要重新 init 来使主题生效。记得备份 `notes` 和 `static` 目录。

更简单的方法是 clone 这个仓库然后用 `/assets/init/themes/paper` 这个目录覆盖工作目录内的 `themes/paper`。

**Comment by HogwartsRico** [comment]
作者速度真快，感谢!
