### ISSUE TITLE
是否支持文件夹？

### ISSUE THREAD

**Issue by kdays** [phoenixlzx/MinoriWiki#2]
比如这样：
minori note uc/account_login

因为API比较多 如果全一个文件夹看着太奇怪了……

**Comment by phoenixlzx** [comment]
已更新，麻烦用 npm 更新包到 0.0.12

需要更新下主题，简单的方法是用仓库下最新的 `/assets/init/themes/paper` 覆盖工作目录下的 `themes/paper`
