### ISSUE TITLE
Can't install by NPM

### ISSUE THREAD

**Issue by kaiwk** [phoenixlzx/MinoriWiki#4]
Hi,

i did the `npm install minori -g`, and it print this:

```
npm ERR! fetch failed https://github.com/mathjax/MathJax/tarball/mathjax-node-2.5.1
npm WARN retry will retry, error on last attempt: Error: connect ETIMEDOUT 192.30.252.161:443
⸨    ░░░░░░░░░░░░░░⸩ ⠧ loadRequestedDeps: WARN retry will retry, error on last a⸨    ░░░░░░░░░░░░░░⸩ ⠦ loadRequestedDeps: WARN retry will retry, error on last attempt: Error: connec⸨    ░░░░░░░░░░░░░░⸩ ⠇ loadRequestedDeps: WARN retry will retry, error on last attempt: Error: connect ETIMEDOUT 192.30.252.161:443
```

and I can install other package via npm.
I'm a newbie to Node, do you know what is the issue here?

**Comment by phoenixlzx** [comment]
It seems you have trouble connecting to github.com. Check your Internet connection, or try install via proxy.

**Comment by kaiwk** [comment]
Yes, it's a problem about the /etc/hosts.  Somehow, I used to add `192.30.252.16 codeload.github.com` to the /etc/hosts, and it may has expired.

Now everything works fine, thank you!
