### ISSUE TITLE
是否能支持多级标签?

### ISSUE THREAD

**Issue by serpicroon** [phoenixlzx/MinoriWiki#6]
首先感谢作者的工作！[\花]
能不能加入对多级标签的支持？
这样issue里多级文件就可以不用显示目录名了^ ^
* programming
  * javascript / grammar
  * javascript / tools
---
* programming
  * javascript
    * grammar
    * tools
  * python

下面这个应该会好看点吧>

**Comment by phoenixlzx** [comment]
这个功能不需要程序本体的支持，修改一下模板就可以实现了。

https://github.com/phoenixlzx/MinoriWiki/blob/master/assets/init/themes/paper/index.ejs#L18
