### ISSUE TITLE
能否在模板中自定义LastUpdate的格式与样式

### ISSUE THREAD

**Issue by jim-kirisame** [phoenixlzx/MinoriWiki#7]
感觉长长的一串这个东西挺难看的，还不能自定义样式（
Last Update: Thu Apr 13 2017 18:38:17 GMT+0800 (中国标准时间) Source File

**Comment by phoenixlzx** [comment]
配置选项在[这里](https://github.com/phoenixlzx/MinoriWiki/blob/e47b50f877c652611b45ed1a8fafff6895a84eea/assets/init/config.yml#L55)。

**Comment by phoenixlzx** [comment]
记得更新 0.0.43，然后 `minori u` 应该就有了。

**Comment by jim-kirisame** [comment]
感谢

话说我还以为这个弃坑了（
